// Size ledger: one table, printed and committed.

import { writeFileSync } from 'node:fs';

const kb = (bytes) => `${(bytes / 1024).toFixed(1)} KiB`;
const num = (bytes) => bytes.toLocaleString('en-US');

function bar(ratio, width = 28) {
  const filled = Math.min(width, Math.round(ratio * width));
  return `[${'#'.repeat(filled)}${'.'.repeat(Math.max(0, width - filled))}]`;
}

export function renderLedger(steps, zipBytes, budget) {
  const label = Math.max(...steps.map((s) => s.label.length));
  const lines = steps.map((s) => `  ${s.label.padEnd(label)}  ${num(s.bytes).padStart(9)}${s.detail ? `   ${s.detail}` : ''}`);
  const over = zipBytes - budget;
  const ratio = zipBytes / budget;
  return [
    '',
    'size ledger',
    ...lines,
    '',
    `  budget      ${num(budget).padStart(9)}  (js13kGames, 13 KiB)`,
    `  zip         ${num(zipBytes).padStart(9)}  ${kb(zipBytes)}`,
    over > 0
      ? `  OVER BY     ${num(over).padStart(9)}  ${bar(ratio)} ${ratio.toFixed(2)}× budget`
      : `  headroom    ${num(-over).padStart(9)}  ${bar(ratio)} ${(ratio * 100).toFixed(1)}% of budget`,
    '',
  ].join('\n');
}

export function writeSizeLedger(file, { steps, zipBytes, budget, source }) {
  const over = zipBytes - budget;
  const rows = steps.map((s) => `| ${s.label.replace(/^\s+/, '&nbsp;&nbsp;')} | ${num(s.bytes)} | ${s.detail || ''} |`);
  writeFileSync(
    file,
    [
      '# Size ledger',
      '',
      'Regenerated by `npm run size`. Numbers are bytes.',
      '',
      `Source: \`${source.branch}\` @ \`${source.commit.slice(0, 8)}\`${source.dirty ? ' (dirty working tree)' : ''}`,
      '',
      '| stage | bytes | note |',
      '| --- | ---: | --- |',
      ...rows,
      '',
      `**Zip: ${num(zipBytes)} bytes** against a ${num(budget)} byte budget — `
      + (over > 0 ? `**${num(over)} over** (${(zipBytes / budget).toFixed(2)}× budget).` : `${num(-over)} to spare.`),
      '',
    ].join('\n'),
  );
}
